version: "3"
services:
       property-app:
           container_name: logansrj/properties
           image: v01/property-app
           restart: always
           build: 
                context: ./back-end
                # Name of the Dockerfile
                dockerfile: Dockerfile.be
           ports:
             - "8080:8080"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'